using System;

namespace GdNet.Domain.Entity
{
    public interface IEntityT<TId> where TId : new()
    {
        TId Id { get; set; }

        DateTime CreatedAt { get; set; }

        /// <summary>
        /// An unique id which will be generated by application worker
        /// </summary>
        string FriendlyId
        {
            get;
            set;
        }

        string CreatedBy { get; set; }

        string Note { get; set; }
    }
}