using System;

namespace GdNet.Domain.Entity
{
    public abstract class EntityBaseT<TId> : IEntityT<TId> where TId : new()
    {
        protected EntityBaseT()
        {
            Id = new TId();
            CreatedAt = DateTime.Now;
        }

        public TId Id { get; set; }

        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// An unique id which will be generated by application worker
        /// </summary>
        public string FriendlyId
        {
            get;
            set;
        }

        public string CreatedBy
        {
            get;
            set;
        }

        public string Note
        {
            get;
            set;
        }
    }
}